/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ardis.view.logico;

import ardis.model.logico.coluna.Coluna;
import ardis.model.logico.indice.Indice;
import ardis.model.logico.indice.TipoIndice;
import ardis.model.logico.tabela.Tabela;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Israel
 */
public class IndiceForm extends javax.swing.JDialog {

    /**
     * Creates new form IndiceForm
     */
    private ColunasTableModel colunasTableModel;
    private Indice indice;
    private Tabela tabela;
    private boolean salvar;

    public IndiceForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        colunasTableModel = new ColunasTableModel();
        initComponents();
    }

    public void novo() {
        clear();
        salvar = false;
        this.indice = new Indice();
        updateColunas();
    }

    public void editar(Indice indice) {
        clear();
        this.indice = indice;
        salvar = false;
        nomeTf.setText(indice.getNome());
        tipoCB.setSelectedItem(indice.getTipo().toString());
        updateColunas();
    }

    private void updateColunas() {
        colunasTableModel.setColunas(tabela.getColunas());
        colunasTableModel.setColunasSelecionadas(indice.getColunas());
        colunasTableModel.updateDataModel();
    }

    private void clear() {
        nomeTf.setText("");
        tipoCB.removeAllItems();
        tipoCB.addItem("INDEX");
        tipoCB.addItem("UNIQUE");
    }

    private boolean formToObject() {
        List<Coluna> colunasSelecionadas = colunasTableModel.getColunasSelecionadas();
        if (colunasSelecionadas.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Você precisa selecionar alguma coluna.", "", JOptionPane.ERROR_MESSAGE);
            return false;
        } else if (colunasRepetidas(colunasSelecionadas)) {
            JOptionPane.showMessageDialog(this, "Você já possui um índice para estas colunas.", "", JOptionPane.ERROR_MESSAGE);
            return false;
        } else {
            indice.setNome(nomeTf.getText());
            indice.setTipo(TipoIndice.valueOf(tipoCB.getSelectedItem().toString()));
            indice.getColunas().clear();
            indice.getColunas().addAll(colunasSelecionadas);
            return true;
        }
    }

    private boolean colunasRepetidas(List<Coluna> colunas) {
        for (Indice indice : tabela.getIndices()) {
            if (indice.getColunas().equals(colunas)) {
                return true;
            }
        }
        return false;
    }

    public boolean isSalvar() {
        return salvar;
    }

    public Indice getIndice() {
        return indice;
    }

    public Tabela getTabela() {
        return tabela;
    }

    public void setTabela(Tabela tabela) {
        this.tabela = tabela;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nomeTf = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tipoCB = new javax.swing.JComboBox();
        salvarBt = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        colunasTable = new javax.swing.JTable();
        cancelarBt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Nome:");

        jLabel2.setText("Tipo:");

        salvarBt.setText("Salvar");
        salvarBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarBtActionPerformed(evt);
            }
        });

        colunasTable.setModel(colunasTableModel);
        jScrollPane1.setViewportView(colunasTable);

        cancelarBt.setText("Cancelar");
        cancelarBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarBtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tipoCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nomeTf)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(salvarBt, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                        .addComponent(cancelarBt)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nomeTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tipoCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salvarBt)
                    .addComponent(cancelarBt))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salvarBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarBtActionPerformed
        if (formToObject()) {
           salvar = true;
            this.dispose();
        }
    }//GEN-LAST:event_salvarBtActionPerformed

    private void cancelarBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarBtActionPerformed
        clear();
        this.dispose();
    }//GEN-LAST:event_cancelarBtActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelarBt;
    private javax.swing.JTable colunasTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nomeTf;
    private javax.swing.JButton salvarBt;
    private javax.swing.JComboBox tipoCB;
    // End of variables declaration//GEN-END:variables
}
