/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ardis.view.logico;

import ardis.model.conceitual.entidade.Entidade;
import ardis.model.logico.coluna.Coluna;
import ardis.model.logico.tabela.Tabela;
import ardis.view.logico.LogicoGraphComponent;
import com.mxgraph.model.mxCell;
import com.mxgraph.swing.handler.mxGraphHandler;

/**
 *
 * @author Davisson
 */
public class ObjetosLogicoMenu extends javax.swing.JPanel {

    /**
     * Creates new form ObjetosLogicoMenu
     */
    
    private LogicoGraphComponent graphComponent;
    
    public ObjetosLogicoMenu() {
        initComponents();
    }

    public void setGraphComponent(LogicoGraphComponent graphComponent) {
        this.graphComponent = graphComponent;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabelaBt = new javax.swing.JButton();
        colunaBt = new javax.swing.JButton();
        relacionamento1to1 = new javax.swing.JButton();
        relacionamento1toN = new javax.swing.JButton();

        tabelaBt.setText("Tabela");
        tabelaBt.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tabelaBt.setContentAreaFilled(false);
        tabelaBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabelaBtActionPerformed(evt);
            }
        });

        colunaBt.setText("Coluna");
        colunaBt.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        colunaBt.setContentAreaFilled(false);
        colunaBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colunaBtActionPerformed(evt);
            }
        });

        relacionamento1to1.setText("Relacionamento 1:1");
        relacionamento1to1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        relacionamento1to1.setContentAreaFilled(false);
        relacionamento1to1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relacionamento1to1ActionPerformed(evt);
            }
        });

        relacionamento1toN.setText("Relacionamento 1:N");
        relacionamento1toN.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        relacionamento1toN.setContentAreaFilled(false);
        relacionamento1toN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relacionamento1toNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tabelaBt, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                    .addComponent(colunaBt, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                    .addComponent(relacionamento1to1, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                    .addComponent(relacionamento1toN, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabelaBt, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(colunaBt, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(relacionamento1to1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(relacionamento1toN, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(163, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tabelaBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tabelaBtActionPerformed
        
        graphComponent.addTabela(new Tabela());
    }//GEN-LAST:event_tabelaBtActionPerformed

    private void colunaBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colunaBtActionPerformed
        
        graphComponent.addColuna(new Coluna());
    }//GEN-LAST:event_colunaBtActionPerformed

    private void relacionamento1to1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relacionamento1to1ActionPerformed

        graphComponent.addRelacionamento11();
    }//GEN-LAST:event_relacionamento1to1ActionPerformed

    private void relacionamento1toNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relacionamento1toNActionPerformed
       
        graphComponent.addRelacionamento1N();
    }//GEN-LAST:event_relacionamento1toNActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton colunaBt;
    private javax.swing.JButton relacionamento1to1;
    private javax.swing.JButton relacionamento1toN;
    private javax.swing.JButton tabelaBt;
    // End of variables declaration//GEN-END:variables
}
