/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ardis.view.conceitual;

import ardis.view.GraphComponent;
import ardis.view.ModeloPanel;
import ardis.view.conceitual.infoTable.ObjetoInfoHandler;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import javax.swing.JSplitPane;

/**
 *
 * @author Davisson
 */
public class ConceitualPanel extends javax.swing.JPanel implements ModeloPanel {

    /**
     * Creates new form ConceitualPanel
     */
    private ConceitualGraphComponent graphComponent;
    private static DetalhesPanel detalhesPanel;
    private static ObjetoInfoHandler infoHandler;

    public ConceitualPanel(ConceitualGraphComponent graphComponent) {
        initComponents();

        setGraphComponent(graphComponent);
        // modeloDetalhesSP.getRightComponent().setVisible(false);

        if (detalhesPanel == null) {
            detalhesPanel = new DetalhesPanel();
        }

        modeloDetalhesSP.setRightComponent(detalhesPanel);
        modeloDetalhesSP.setDividerLocation(900);
        if (infoHandler == null) {
            infoHandler = new ObjetoInfoHandler(detalhesPanel, modeloDetalhesSP);
        }
        infoHandler.addGraphComponent(graphComponent);
        modeloDetalhesSP.getRightComponent().setVisible(false);


    }

    public ConceitualGraphComponent getGraphComponent() {
        return graphComponent;
    }

    @Override
    public void setGraphComponent(GraphComponent graphComponent) {
        this.graphComponent = (ConceitualGraphComponent) graphComponent;
        modeloDetalhesSP.setLeftComponent(graphComponent);
    }

    public JSplitPane getSplitPane() {
        return modeloDetalhesSP;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        modeloDetalhesSP = new javax.swing.JSplitPane();

        modeloDetalhesSP.setDividerSize(8);
        modeloDetalhesSP.setOneTouchExpandable(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(modeloDetalhesSP, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(modeloDetalhesSP, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSplitPane modeloDetalhesSP;
    // End of variables declaration//GEN-END:variables

    public void focusGained() {
        infoHandler.setGraphComponentAtual(graphComponent);
    }
}
