/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ardis.view.conceitual;

import ardis.view.conceitual.infoTable.AbstractInfoTable;

/**
 *
 * @author Davisson
 */
public class DetalhesPanel extends javax.swing.JPanel {

    public AbstractInfoTable table;

    /**
     * Creates new form ObjetoInfoPanel
     */
    public DetalhesPanel() {
        initComponents();
     
    }

    public AbstractInfoTable getTable() {
        return table;
    }

    public void setTable(AbstractInfoTable table) {
        if (this.table != null) {
            remove(this.table);
        }
        //table.setBounds(0, 0, 150, 100);
        // add(table);
        tabelaSP.setViewportView(table);
        this.table = table;
        repaint();
    }

    public void removeTable() {
        if (this.table != null) {
            remove(this.table);
        }
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabelaSP = new javax.swing.JScrollPane();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabelaSP, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabelaSP, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane tabelaSP;
    // End of variables declaration//GEN-END:variables
}
