/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ardis.view.conceitual;

import ardis.model.conceitual.atributo.Atributo;
import ardis.model.conceitual.atributo.composto.AtributoComposto;
import ardis.model.conceitual.atributo.composto.AtributoCompostoImpl;
import ardis.model.conceitual.atributo.multivalorado.AtributoMultivalorado;
import ardis.model.conceitual.entidade.Entidade;
import ardis.model.conceitual.entidade.entidadeAssociativa.EntidadeAssociativa;
import ardis.view.adders.RelacionamentoAdder.RelacionamentoAddType;
import ardis.view.conceitual.ConceitualGraphComponent;

/**
 *
 * @author Davisson
 */
public class ObjetosConceitualMenu extends javax.swing.JPanel {

    /**
     * Creates new form ObjetosConceitualMenu
     */
    private ConceitualGraphComponent conceitualPanel;

    public ObjetosConceitualMenu() {
        initComponents();
    }

    public void setConceitualPanel(ConceitualGraphComponent conceitualPanel) {
        this.conceitualPanel = conceitualPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        entidadeBt = new javax.swing.JButton();
        relacionamentoBt = new javax.swing.JButton();
        entidadeAssociativaBt = new javax.swing.JButton();
        atributoBt = new javax.swing.JButton();
        especializacaoBt = new javax.swing.JButton();
        atributoIdentificadorBt = new javax.swing.JButton();
        atributoCompostoBt = new javax.swing.JButton();
        atributoMultivaloradoBt = new javax.swing.JButton();
        relacionarBt = new javax.swing.JButton();
        especializacaoExclusivaBt = new javax.swing.JButton();
        especializacaoNaoExclusivaBt2 = new javax.swing.JButton();
        autoRelacionarBt = new javax.swing.JButton();

        entidadeBt.setText("Entidade");
        entidadeBt.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        entidadeBt.setContentAreaFilled(false);
        entidadeBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entidadeBtActionPerformed(evt);
            }
        });

        relacionamentoBt.setText("Relacionamento");
        relacionamentoBt.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        relacionamentoBt.setContentAreaFilled(false);
        relacionamentoBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relacionamentoBtActionPerformed(evt);
            }
        });

        entidadeAssociativaBt.setText("Entidade Associativa");
        entidadeAssociativaBt.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        entidadeAssociativaBt.setContentAreaFilled(false);
        entidadeAssociativaBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entidadeAssociativaBtActionPerformed(evt);
            }
        });

        atributoBt.setText("Atributo");
        atributoBt.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        atributoBt.setContentAreaFilled(false);
        atributoBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atributoBtActionPerformed(evt);
            }
        });

        especializacaoBt.setText("Especialização");
        especializacaoBt.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        especializacaoBt.setContentAreaFilled(false);
        especializacaoBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                especializacaoBtActionPerformed(evt);
            }
        });

        atributoIdentificadorBt.setText("Atributo Identificador");
        atributoIdentificadorBt.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        atributoIdentificadorBt.setContentAreaFilled(false);
        atributoIdentificadorBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atributoIdentificadorBtActionPerformed(evt);
            }
        });

        atributoCompostoBt.setText("Atributo Composto");
        atributoCompostoBt.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        atributoCompostoBt.setContentAreaFilled(false);
        atributoCompostoBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atributoCompostoBtActionPerformed(evt);
            }
        });

        atributoMultivaloradoBt.setText("Atributo Multivalorado");
        atributoMultivaloradoBt.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        atributoMultivaloradoBt.setContentAreaFilled(false);
        atributoMultivaloradoBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atributoMultivaloradoBtActionPerformed(evt);
            }
        });

        relacionarBt.setText(" Relacionar");
        relacionarBt.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        relacionarBt.setContentAreaFilled(false);
        relacionarBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relacionarBtActionPerformed(evt);
            }
        });

        especializacaoExclusivaBt.setText("Especialização Exclusiva");
        especializacaoExclusivaBt.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        especializacaoExclusivaBt.setContentAreaFilled(false);
        especializacaoExclusivaBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                especializacaoExclusivaBtActionPerformed(evt);
            }
        });

        especializacaoNaoExclusivaBt2.setText("Especialização !Exclusiva");
        especializacaoNaoExclusivaBt2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        especializacaoNaoExclusivaBt2.setContentAreaFilled(false);
        especializacaoNaoExclusivaBt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                especializacaoNaoExclusivaBt2ActionPerformed(evt);
            }
        });

        autoRelacionarBt.setText("Auto - Relacionar");
        autoRelacionarBt.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        autoRelacionarBt.setContentAreaFilled(false);
        autoRelacionarBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autoRelacionarBtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(entidadeBt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(atributoBt, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                    .addComponent(especializacaoBt, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                    .addComponent(atributoIdentificadorBt, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                    .addComponent(atributoCompostoBt, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                    .addComponent(relacionamentoBt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(relacionarBt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(atributoMultivaloradoBt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(entidadeAssociativaBt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(especializacaoExclusivaBt, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                    .addComponent(especializacaoNaoExclusivaBt2, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                    .addComponent(autoRelacionarBt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(entidadeBt, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(relacionamentoBt, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(entidadeAssociativaBt, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(especializacaoBt, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(especializacaoExclusivaBt, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(especializacaoNaoExclusivaBt2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(atributoBt, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(atributoIdentificadorBt, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(atributoCompostoBt, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(atributoMultivaloradoBt, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(autoRelacionarBt, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(relacionarBt, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void entidadeBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entidadeBtActionPerformed

        conceitualPanel.chooseEntidade(Entidade.class);
    }//GEN-LAST:event_entidadeBtActionPerformed

    private void relacionamentoBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relacionamentoBtActionPerformed
        conceitualPanel.chooseRelacionamento(RelacionamentoAddType.ALONE);
    }//GEN-LAST:event_relacionamentoBtActionPerformed

    private void entidadeAssociativaBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entidadeAssociativaBtActionPerformed
        conceitualPanel.chooseEntidade(EntidadeAssociativa.class);
    }//GEN-LAST:event_entidadeAssociativaBtActionPerformed

    private void atributoBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atributoBtActionPerformed

        conceitualPanel.chooseAtributo(new Atributo());
    }//GEN-LAST:event_atributoBtActionPerformed

    private void especializacaoBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_especializacaoBtActionPerformed
        conceitualPanel.chooseEspecializacao(0);
    }//GEN-LAST:event_especializacaoBtActionPerformed

    private void atributoIdentificadorBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atributoIdentificadorBtActionPerformed
        conceitualPanel.chooseAtributo(new Atributo(true));
    }//GEN-LAST:event_atributoIdentificadorBtActionPerformed

    private void atributoCompostoBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atributoCompostoBtActionPerformed
        conceitualPanel.chooseAtributo(new AtributoCompostoImpl());
    }//GEN-LAST:event_atributoCompostoBtActionPerformed

    private void atributoMultivaloradoBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atributoMultivaloradoBtActionPerformed
        conceitualPanel.chooseAtributo(new AtributoMultivalorado());
    }//GEN-LAST:event_atributoMultivaloradoBtActionPerformed

    private void relacionarBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relacionarBtActionPerformed
        conceitualPanel.chooseRelacionamento(RelacionamentoAddType.CONNECT);
    }//GEN-LAST:event_relacionarBtActionPerformed

    private void especializacaoExclusivaBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_especializacaoExclusivaBtActionPerformed
        conceitualPanel.chooseEspecializacao(2);
    }//GEN-LAST:event_especializacaoExclusivaBtActionPerformed

    private void especializacaoNaoExclusivaBt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_especializacaoNaoExclusivaBt2ActionPerformed
        conceitualPanel.chooseEspecializacao(1);
    }//GEN-LAST:event_especializacaoNaoExclusivaBt2ActionPerformed

    private void autoRelacionarBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autoRelacionarBtActionPerformed
        conceitualPanel.chooseRelacionamento(RelacionamentoAddType.AUTO);
    }//GEN-LAST:event_autoRelacionarBtActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atributoBt;
    private javax.swing.JButton atributoCompostoBt;
    private javax.swing.JButton atributoIdentificadorBt;
    private javax.swing.JButton atributoMultivaloradoBt;
    private javax.swing.JButton autoRelacionarBt;
    private javax.swing.JButton entidadeAssociativaBt;
    private javax.swing.JButton entidadeBt;
    private javax.swing.JButton especializacaoBt;
    private javax.swing.JButton especializacaoExclusivaBt;
    private javax.swing.JButton especializacaoNaoExclusivaBt2;
    private javax.swing.JButton relacionamentoBt;
    private javax.swing.JButton relacionarBt;
    // End of variables declaration//GEN-END:variables
}
